<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="EPINPUNW00A3" failures="2" tests="2" name="Default test" time="72.597" errors="0" timestamp="2021-03-02T00:23:22 IST">
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="64.183">
    <failure type="java.lang.AssertionError" message="expected [0] but found [9]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [9]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.win.stepdefs.CalculatorStepDef.validateResultAdd(CalculatorStepDef.java:31)
at ✽.Validate the Result for addition(file:///C:/Users/Elango_Venkateshan/eclipse-workspace/WallGreens_Automation/src/test/resources/features/WinAppDriverSample.feature:7)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <testcase classname="io.cucumber.testng.AbstractTestNGCucumberTests" name="runScenario" time="7.865">
    <failure type="java.lang.AssertionError" message="expected [0] but found [9]">
      <![CDATA[java.lang.AssertionError: expected [0] but found [9]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.assertEqualsImpl(Assert.java:136)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:575)
at org.testng.Assert.assertEquals(Assert.java:585)
at com.win.stepdefs.CalculatorStepDef.validateResultSubtract(CalculatorStepDef.java:40)
at ✽.Validate the Result for subtraction(file:///C:/Users/Elango_Venkateshan/eclipse-workspace/WallGreens_Automation/src/test/resources/features/WinAppDriverSample.feature:13)
]]>
    </failure>
  </testcase> <!-- runScenario -->
</testsuite> <!-- Default test -->
